name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
env:
  CARGO_TERM_COLOR: always

jobs:
  rele:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: cool
       run: cargo build --release --offline
     
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
